name: run blackout.py

on:
  #schedule:
  #  - cron: "*/20 5-22 * * *" # Every X min past hours 5-22 UTC
  workflow_dispatch # manually

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: install python packages
        run: pip install -r requirements.txt

      - name: execute py script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python blackout.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action [bot]"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated schedule.json" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
